### ISSUE TITLE
Generate link creates error

### ISSUE THREAD

**Issue by acateon** [KoalaV2/gettime#95]
Trying to create a private link creates the following error:

```
TIME OF ERROR : 2023-03-07-13-40-41

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "main.py", line 1414, in INDEX
    initSchool = int(initSchool)
ValueError: invalid literal for int() with base 10: 'Almåsgymnasiet'
```

**Comment by KoalaV2** [comment]
Seems like i missed this when converting from the old IDs, fixed in next commit. Will now add a test for private links too. Thanks!

**Comment by KoalaV2** [comment]
Also updated README with working example link.
